const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert/strict'),c={};c.window=c;vm.createContext(c);for(const f of ['business-engine.js','gps-templates.js','gps-engine.js','touch-library.js','touch-engine.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/life-by-design',f),'utf8'),c);
const B=c.LBDBusiness,G=c.LBDGPS,E=c.LBDTouch,b=B.defaults();Object.assign(b,{goalMode:'manual',manualGoal:240000,weeks:39,sellerShare:67,sellerApptSigned:73,buyerApptSigned:48});b.saved={fingerprint:JSON.stringify({...b,page:0,saved:null,activeGoal:b.manualGoal})};const bs=G.source(b,null),g=G.generate({blueprint:'brand_builder',start:'2027-12',mets:103,returnRate:5,minutes:90},bs),gps={plan:g,edits:{}};gps.saved={signature:JSON.stringify([g,{}])};const src=E.source(gps,b,null);
assert.equal(g.goal.weeklyAppointments,bs.plan.sellerWeekly+bs.plan.buyerWeekly);assert.equal(g.goal.weeklySellerAppointments,bs.plan.sellerWeekly);assert(g.priorities[0].strategies[1].text.includes('Reserve '+bs.plan.weekly+' appointment slots'));
for(const start of ['2027-12','2028-01','2029-07'])for(const cadence of [36,72])for(const events of [2,3,4]){
 const s={...src,gps:{...g,input:{...g.input,start}}},input={...E.defaults(),cadence,events},p=E.generate(input,s);
 assert.equal(p.slots.length,cadence);assert.equal(p.slots.filter(x=>x.kind==='quarterly').length,4);assert.equal(p.slots.filter(x=>x.kind==='newsletter').length,12);assert.equal(p.slots.filter(x=>x.kind==='event').length,events);assert.equal(p.slots.filter(x=>x.kind==='event-rsvp').length,events);assert.equal(new Set(p.slots.map(s=>s.id)).size,cadence);assert.equal(Object.values(p.segments).reduce((a,b)=>a+b),103);assert(p.slots.every(s=>s.month>=0&&s.month<12));assert.deepEqual(p,E.generate(input,s));
 for(const q of p.quarters)assert(q.groups.every(x=>x.date>=q.start&&x.date<=q.end));
 for(const s of p.slots.filter(s=>s.kind==='content'))assert(input.preferences.includes(s.family));
 for(const f of ['buyer_opportunity','seller_opportunity'])for(let q=0;q<4;q++)assert(p.slots.filter(s=>s.kind==='content'&&s.family===f&&Math.floor(s.month/3)===q).length<=1);
}
for(const mets of [0,1,2,7,103,1000000]){const i={...E.defaults(),advocates:33,strong:33,warm:33,weak:1},counts=E.segmentCounts(i,mets);assert.equal(Object.values(counts).reduce((a,b)=>a+b),mets);assert(Object.values(counts).every(Number.isInteger));}
assert.throws(()=>E.generate({...E.defaults(),warm:0},src),/100%/);assert.throws(()=>E.generate({...E.defaults(),preferences:[]},src),/preference/);assert.throws(()=>E.generate({...E.defaults(),preferences:['market_review'],cadence:72},src),/preference|variety/);assert.throws(()=>E.generate({...E.defaults(),eventDates:['2027-12-02','2028-05-20']},src),/30 days/);assert.throws(()=>E.generate({...E.defaults(),eventDates:['2028-05-20','2028-05-25']},src),/40 days/);
const p=E.generate(E.defaults(),src),vary=E.generate({...E.defaults(),seed:8271},src);assert.notEqual(JSON.stringify(p.slots),JSON.stringify(vary.slots));const slot=p.slots.find(s=>E.alternatives(p,s.id).length),alt=E.alternatives(p,slot.id)[0],changed=E.replace(p,slot.id,alt.id);assert.equal(changed.slots.length,36);assert.equal(changed.slots.find(x=>x.id===slot.id).date,slot.date);assert.equal(changed.slots.filter((s,i)=>JSON.stringify(s)!==JSON.stringify(p.slots[i])).length,1);assert.throws(()=>E.replace(p,p.slots.find(s=>s.locked).id,alt.id));
assert.throws(()=>E.source({...gps,edits:{x:'edit'}},b,null),/save/);assert.throws(()=>E.source(gps,{...b,weeks:30},null),/changed/);
console.log('PASS preferences, deterministic variety, one-slot replacement, 18 calendar scenarios, quarterly calls, event journeys, exact segment rounding, GPS weekly appointment handoff, stale-source checks');
