import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import '../public/life-by-design/business-engine.js';
import '../public/life-by-design/gps-templates.js';
import '../public/life-by-design/gps-engine.js';
import '../public/life-by-design/touch-library.js';
import '../public/life-by-design/touch-engine.js';
const E=globalThis.LBDBusiness;
const requireThat=(ok,msg)=>{if(!ok)throw new Error(msg);};
export function validatePlan(data){
 requireThat(data&&JSON.stringify(data).length<700000,'This plan is too large to send.');
 const {profile,life,business,gps,touch,schedule}=data;
 requireThat(profile&&typeof profile.name==='string'&&profile.name.trim()&&profile.name.length<=100,'Add your name first.');
 requireThat(typeof profile.email==='string'&&profile.email.length<=254&&/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(profile.email),'Enter a valid delivery email.');
 const src=globalThis.LBDGPS.source(business,life);
 requireThat(gps?.saved?.signature===JSON.stringify([gps?.plan,gps?.edits])&&gps?.plan?.sourceFingerprint===src.fingerprint&&gps?.plan?.templateVersion===globalThis.LBDGPSTemplates.version,'Refresh and save your GPS before sending.');
 globalThis.LBDGPS.validate(gps.plan.input);
 requireThat(touch?.saved?.signature===JSON.stringify([touch?.plan,touch?.edits])&&touch?.plan?.sourceSignature===gps.saved.signature&&touch?.plan?.version===globalThis.LBDTouch.VERSION,'Refresh and save your touch plan before sending.');
 requireThat(Array.isArray(touch.plan.slots)&&[36,72].includes(touch.plan.slots.length),'Review your complete touch calendar.');
 requireThat(schedule?.savedAt&&schedule.sourceKey===gps.saved.signature&&Array.isArray(schedule.blocks)&&schedule.blocks.length<=60,'Save your current weekly routine before sending.');
 const active=schedule.blocks.filter(b=>b.enabled),minute=t=>/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(t)?Number(t.slice(0,2))*60+Number(t.slice(3)):NaN;
 for(const b of active){requireThat(typeof b.name==='string'&&b.name.length<=100&&b.days?.length&&b.days.every(d=>Number.isInteger(d)&&d>=0&&d<=6),'Review your weekly routine blocks.');let a=minute(b.start),z=minute(b.end);requireThat(a>=0&&z<=1440&&z>a&&a%15===0&&z%15===0,'Resolve invalid times in your routine.');for(const d of b.days){requireThat(!schedule.off?.includes(d),'Resolve routine blocks on a day off.');for(const o of active)if(o!==b&&o.days.includes(d))requireThat(!(a<minute(o.end)&&minute(o.start)<z),'Resolve overlapping routine blocks before sending.');}}
 requireThat(gps.plan.priorities?.length===3,'Review your GPS priorities.');
 for(const p of gps.plan.priorities){requireThat(p.strategies?.length===5,'Review your GPS strategies.');for(const s of p.strategies)requireThat(typeof(gps.edits[s.id]??s.text)==='string'&&(gps.edits[s.id]??s.text).length<=4000,'A GPS strategy is too long.');}
 return {...data,src};
}
export async function workbook(raw){
 const d=validatePlan(raw),p=d.src.plan,g=d.gps.plan,t=d.touch.plan;
 const pdf=await PDFDocument.create();pdf.setTitle('My Complete Business Plan');pdf.setAuthor('The Ascending Agent');
 const normal=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),title=await pdf.embedFont(StandardFonts.TimesRoman);
 const color=h=>rgb(parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4),16)/255),ink=color('0e2433'),green=color('23765f'),muted=color('64747c'),soft=color('edf4ef'),gold=color('c7a44b');
 const clean=s=>String(s??'').replace(/\*\*/g,'').replace(/[\u2010-\u2015]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/→/g,' to ').replace(/[^\x20-\x7e\xa0-\xff\n]/g,' ');
 let page,y=0,section='';
 const draw=(s,x,yy,size=10,font=normal,c=ink)=>page.drawText(clean(s),{x,y:792-yy-size,size,font,color:c});
 function newPage(name){section=name;page=pdf.addPage([612,792]);page.drawRectangle({x:42,y:733,width:30,height:30,color:ink});draw('L',51,27,23,title,gold);draw('Life by Design',84,29,12,bold);draw('THE ASCENDING AGENT',84,48,7,normal,muted);draw(name.toUpperCase(),48,94,9,bold,green);y=121;}
 function lines(s,width=516,size=11,font=normal){const result=[];for(const para of clean(s).split('\n')){let line='';for(const word of para.split(/\s+/)){if(font.widthOfTextAtSize((line?line+' ':'')+word,size)>width&&line){result.push(line);line='';}if(font.widthOfTextAtSize(word,size)>width){for(const ch of word){if(font.widthOfTextAtSize(line+ch,size)>width){result.push(line);line='';}line+=ch;}}else line+=(line?' ':'')+word;}result.push(line);}return result;}
 function room(h){if(y+h>719)newPage(section+' / continued');}
 function paragraph(s,size=11,font=normal,c=ink){for(const l of lines(s,516,size,font)){room(size*1.5);draw(l,48,y,size,font,c);y+=size*1.5;}y+=8;}
 function heading(s){paragraph(s,25,title);y+=8;}
 function row(label,value){const ls=lines(label,286,10),vs=lines(value,200,10,bold),h=Math.max(ls.length,vs.length)*15+17;room(h);ls.forEach((v,i)=>draw(v,58,y+7+i*15,10));vs.forEach((v,i)=>draw(v,354,y+7+i*15,10,bold));y+=h;page.drawLine({start:{x:48,y:792-y},end:{x:564,y:792-y},thickness:.5,color:soft});}
 function hero(label,value,detail){room(100);page.drawRectangle({x:48,y:792-y-100,width:516,height:100,color:ink});draw(label,65,y+13,9,bold,gold);draw(value,65,y+35,30,bold,rgb(1,1,1));draw(detail,65,y+78,10,normal,rgb(.8,.86,.86));y+=121;}
 const money=n=>'$'+Math.round(Number(n)||0).toLocaleString('en-US'),n=x=>Math.ceil(x).toLocaleString('en-US');
 newPage('My complete plan');heading('Build a business that funds your life by design.');paragraph('Prepared for '+d.profile.name,18,bold);paragraph(d.profile.email,11,normal,muted);paragraph('12-month plan beginning '+g.input.start+' | '+g.blueprintName);hero('ANNUAL GROSS COMMISSION INCOME',money(p.gci),n(p.sales)+' closed units | '+d.src.weeks+' working weeks');paragraph('Your life. Your business. Your next steps.',19,title);['Life by Design','Economic Model','GPS Business Plan','Complete Database Touch Calendar','Weekly Business Routine','4-1-1 and Monthly Four Conversations'].forEach((s,i)=>row(String(i+1).padStart(2,'0'),s));
 newPage('01 / Life by Design');heading('The life your business funds.');const life=E.lifeTarget(d.life);if(life.error){paragraph('Your Economic Model uses a manually entered owner income goal. No saved Life by Design breakdown was supplied.');hero('OWNER INCOME GOAL',money(d.business.manualGoal),'Before personal taxes');}else{hero('ANNUAL LIFE BY DESIGN TARGET',money(life.value),money(life.value/12)+' per month, including the tax reserve');const labels={foundation:'Living expenses',security:'Safety + freedom',lifestyle:'Lifestyle',impact:'Giving',future:'Future goals'};for(const [key,label]of Object.entries(labels)){let a=(d.life.sections[key]||[]).reduce((sum,x)=>sum+Number(String(x.amount||0).replace(/,/g,''))*(x.frequency==='annual'?1:12),0);row(label,money(a/12)+' / month | '+money(a)+' / year');}row('Tax reserve',money(life.taxes/12)+' / month | '+money(life.taxes)+' / year');paragraph('Planning estimates only. Confirm tax assumptions with your tax professional.',10,normal,muted);}
 newPage('02 / Economic Model');heading('Your Economic Model for Your Business Goal');row('Owner income before personal taxes',money(p.profit));row('Cost of sales',money(p.cos));row('Operating expenses',money(p.opex));row('Annual gross commission income',money(p.gci));row('Estimated volume',money(p.volume));for(const side of ['seller','buyer']){room(290);y+=16;paragraph(side==='seller'?'Seller Business':'Buyer Business',18,title);const pref=side;row('Closed units needed',n(p[pref+'Sales']));row('Contracts needed',n(p[pref+'Contracts']));row('Signed agreements needed',n(p[pref+'Signed']));row('Appointments needed / year',n(p[pref+'Appointments']));row('Appointments needed / month',n(p[pref+'Monthly']));row('Appointments needed / working week',n(p[pref+'Weekly']));}paragraph('Monthly goals are rounded planning targets, not a seasonal forecast.',10,normal,muted);
 newPage('03 / GPS Business Plan');heading('One goal. Three priorities.');paragraph('Take '+g.goal.listings+' listings and close '+g.goal.closings+' total units for '+money(g.goal.gci)+' GCI and '+money(g.goal.profit)+' owner profit before personal taxes.');for(const [i,pr]of g.priorities.entries()){room(100);paragraph('PRIORITY '+(i+1),9,bold,green);paragraph(pr.title,18,title);for(const [j,s]of pr.strategies.entries()){paragraph((j+1)+'. '+s.title,11,bold);paragraph(d.gps.edits[s.id]??s.text,10);}}row('Current met database',g.input.mets);row('Database goal',g.database.target);row('Net met additions / month',g.database.monthly);
 newPage('04 / Database Touch Plan');heading('Your '+t.input.cadence+'-Touch Relationship Plan');paragraph(t.mets+' met contacts | Starts '+t.start);paragraph('Four personal calls to every met each year, using the DTD2 rotation. Honor each contact\'s communication preferences.');for(const [i,q]of t.quarters.entries()){room(140);paragraph('Quarter '+(i+1)+' call windows',15,bold);for(const group of q.groups)row(group.date,group.letters);}
 for(let month=0;month<12;month++){newPage('04 / Touch Calendar');heading('Month '+(month+1)+' of your touch plan');for(const slot of t.slots.filter(s=>s.month===month)){const x={...slot,...d.touch.edits[slot.id]};room(100);paragraph(x.date+' | '+x.channel,9,bold,green);paragraph(x.title,15,title);paragraph(x.purpose,10);if(x.nextAction)paragraph('Conversation starter: '+x.nextAction,10);if(x.prerequisites)paragraph('Use when: '+x.prerequisites,10,normal,muted);if(x.fallback)paragraph('Alternative: '+x.fallback,10,normal,muted);if(x.notes)paragraph('My notes: '+x.notes,10);}}
 const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];const clock=s=>{let[h,m]=s.split(':').map(Number);return(h%12||12)+':'+String(m).padStart(2,'0')+' '+(h<12?'AM':'PM');};newPage('05 / Weekly Business Routine');heading('Give your goals a place on the calendar.');paragraph(g.goal.weeklyAppointments+' appointment slots needed per working week. Move placeholders as actual appointments are scheduled.');for(let i=0;i<7;i++){room(70);paragraph(days[i]+(d.schedule.off.includes(i)?' - Day off':''),16,title);const blocks=d.schedule.blocks.filter(b=>b.enabled&&b.days.includes(i)).sort((a,b)=>a.start.localeCompare(b.start));for(const b of blocks)row(clock(b.start)+' - '+clock(b.end),b.name);if(!blocks.length)paragraph('No scheduled blocks.',10,normal,muted);}if(d.schedule.personal)paragraph('Personal commitments: '+d.schedule.personal,10);
 newPage('06 / Annual 4-1-1');heading('Your annual goals');const annual=[['Leads generated',n(p.sales*10)],['Listings / signed agreements',n(p.sellerSigned+p.buyerSigned)],['Contracts written',n(p.sellerContracts+p.buyerContracts)],['Contracts closed',n(p.sales)],['Money / GCI',money(p.gci)],['People','________________________'],['Systems and tools','________________________'],['Personal education','________________________']];for(const r of annual)row(...r);
 newPage('07 / Monthly and Weekly 4-1-1');heading('Turn priorities into commitments.');paragraph('Month: __________________________');row('Leads generated',n(p.sales*10/12));row('Appointments needed',p.monthly);row('Contracts written',p.sellerContractsMonthly+p.buyerContractsMonthly);row('Signed listings and buyer commitments',p.sellerAgreementsMonthly+p.buyerAgreementsMonthly);row('Closed units',E.up(p.sellerSales/12)+E.up(p.buyerSales/12));row('GCI',money(p.gci/12));row('People','________________________');row('Systems and tools','________________________');row('Personal education','________________________');paragraph('Monthly figures are planning averages; choose priorities from your GPS.',10,normal,muted);for(let i=1;i<=3;i++)row('Monthly priority '+i,'________________________');for(let i=1;i<=5;i++){room(53);row('Week '+i+' commitments','________________________');}
 newPage('08 / Monthly Four Conversations');heading('Know your goal. See your progress.');paragraph('Month: __________________________');const rows=[['Appointments',p.monthly],['Listings + buyer commitments',p.sellerAgreementsMonthly+p.buyerAgreementsMonthly],['Closed units',E.up(p.sellerSales/12)+E.up(p.buyerSales/12)],['GCI',money(p.gci/12)]];const xx=[48,258,328,408,494];for(let i=0;i<5;i++)draw(['Monthly result','Goal','Actual','% of goal','GAP'][i],xx[i],y,10,bold,green);y+=32;for(const r of rows){draw(r[0],48,y,10);draw(String(r[1]),258,y,10,bold);for(let i=2;i<5;i++)draw('________',xx[i],y,10,normal,muted);y+= sixty();}paragraph('Percent of Goal = Actual / Goal x 100. GAP = Goal - Actual. A negative gap means ahead of goal. For a zero goal, write N/A.',10,normal,muted);paragraph('What will I adjust next month?',18,title);row('','________________________________');
 function sixty(){return 60;}
 for(const [i,pg]of pdf.getPages().entries()){page=pg;draw('Life by Design | '+d.profile.name,48,756,8,normal,muted);draw((i+1)+' / '+pdf.getPageCount(),520,756,8,normal,muted);}
 return Buffer.from(await pdf.save());
}
